language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '14'
  - '12'
  - '10'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm run coverage
  - codecov
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
